version: '3.2'

services:
    gomf:
        image: gomf
        build:
            context: .
            dockerfile: ./docker/go/Dockerfile
        restart: always
        ports: 
            - "8080:8080"
        volumes:
            - type: bind
              source: /gomf/files
              target: /files
    db:
        image: db
        build: 
            context: ./docker/postgres
        restart: always
        ports:
            - "8001:5432"
        environment:
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - type: bind
              source: /gomf/postgres-data
              target: /var/lib/postgresql/data
    web:
        image: nginx
        restart: always
        build:
            context: ./docker/nginx
        volumes:
            - type: bind
              source: /gomf/files
              target: /gomf/files
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=165.22.38.246
            - NGINX_PORT=80

